### ISSUE TITLE
"Preparing memory." on booting cpmish on an NC200.

### ISSUE THREAD

**Issue by FrankTaylorLieder** [davidgiven/cpmish#10]
I tried to boot cpmish on my NC200 and just got a message saying "Preparing memory." in a centralised box on the NC screen. The disk drive motor stays on and the machine power button no longer works... I assume it's crashed.

I created a boot disk on Linux (USB disk drive) using:
ufiformat -f 720 /dev/sda
dd if=nc200.img of=/dev/sda

I've tried the image in the current github distribution. I also managed (after some hacking) to build the image (on Raspbian). Both images have the same results.

Any ideas?

Many thanks,
Frank.

**Comment by davidgiven** [comment]
Blast. That's what happens if you format the disk on the NC200. I believe it's a problem in that the NC200 uses non-standard sector skew and for some reason these don't load; not sure why. I've been trying to avoid finding out because debugging that stuff is painful.

I suspect that your USB floppy drive uses a similar non-standard sector skew. Do you have another one you can try?

**Comment by FrankTaylorLieder** [comment]
Thanks. I'll see if I can dig out an old laptop and format the disk there.

**Comment by FrankTaylorLieder** [comment]
Excellent. Having found an old laptop and booted in safe mode as the BIOS was crashing in a full boot. I formatted the disk... and it now works!

Is sector skew a function of the hardware on the drive, or the software driving the format?

**Comment by davidgiven** [comment]
It's a software issue, but USB drives typically don't allow you to configure this (although I could be wrong, the UFI spec is madness). I should probably investigate what's happening here...

**Comment by Allisontheolder** [comment]
Same here, Bios has a few linkage errors that manifest themselves depending on platform.
Worked ok on bare S100 crate with FD1791 (CCS California Computers Corp) but crashed 
on a SB180.

BIOS is the one area that will be hardware specific.

**Comment by davidgiven** [comment]
This should now be fixed. I rewrote, well, everything which was wrong which was quite a lot. Unfortunately the downside is that disks formatted on a PC have much poorer performance than those formatted on the NC200 itself; both will work, though. See `arch/nc200/README.md` for information.
