### ISSUE TITLE
CP/M tm is a trademark and itself is copyrighted by DRI and it heirs.

### ISSUE THREAD

**Issue by Allisontheolder** [davidgiven/cpmish#11]
Even the term "CP/M" is copyrighted as well as trademarked.

Not unlike "Xerox copy" has become lexicon in english its sitll property of Xerox corporation.
So all copies of docs and listed must have a note of attribution of the work and trademarks of DRI.

**Comment by davidgiven** [comment]
Good point, and easily fixed --- I'll find the right boilerplate and add it to the docs.

**Comment by davidgiven** [comment]
Hang on, I haven't done this yet!
