### ISSUE TITLE
What CP/M hosted C compiler is used?

### ISSUE THREAD

**Issue by Allisontheolder** [davidgiven/cpmish#12]
I've tried BDS-C and SmallC and tons of error complaining of format and structure and libs.
HitechTec C and Aztec C are pending.
Likely can compile on the PC using SDCC but that far from native.

**Comment by davidgiven** [comment]
None. Everything's cross-compiled using the ACK --- see the README.md for instructions. The only ANSI C CP/M compiler I know of is Hitech C, which is unusable because it's closed-source (and now unavailable). If you know of any other ANSI C compilers I'd love to know of them.

**Comment by Allisontheolder** [comment]
ANSI C has a big issue it happened after CP/M so no.
I can't compile ACK on a CP/M system then,  A port to CP/M looks like loads 
of fun and unknown for resulting size at present. I have the stuff.

A tool that closed source is not an issue for someone with a license or has read 
the existing one.  I am the former so doing it on a CP/M system has more appeal.
Cross asembly on linux is less appealing.

**Comment by Allisontheolder** [comment]
I was talking native Z80/Zsystem not PC.  What's wrong with SDCC or GCC on Linux
they are open and source.

On Z80 systems I have most of the good compilers and a few are open source like SmallC
and released like Hitech-c and BDS-C.  Some of that is closed because the source is just 
plain lost.  They are widely available as the distributed files (CP/M  .com files).

**Comment by davidgiven** [comment]
Right now cpmish is intended to be cross-compiled from Linux, not self-hosted on CP/M --- maybe one day.

As for sdcc and gcc --- I used to use sdcc but I got fed up with the bugs and weird behaviour; and gcc can't generate Z80 or 8080 code. The ACK generates 8080 code (and I am also its maintainer), and was an easy drop-in replacement.

**Comment by Allisontheolder** [comment]
Not solvable.
