### ISSUE TITLE
Find an editor

### ISSUE THREAD

**Issue by davidgiven** [davidgiven/cpmish#3]
The last remaining piece of the core system.

I did find te, which is GPL: http://texteditors.org/cgi-bin/wiki.pl?Te

However, it currently won't build with the ACK because the ACK's stdio library doesn't work with CP/M.

**Comment by Allisontheolder** [comment]
TECO if you can find it is a very power line editor.

Another released to PD is VEDIT.  When configured for the terminal in use its a 
full screen editor with a TECO complete command line interface.    when looking for it do not confuse it with vEDIT and VEDIT for Winders as they are not the same product or owner, they took the name as a generic.  The later versions are modern PC and not CP/M, very good however.

That's the one you want.  http://www.classiccmp.org/cpmarchives/cpm/mirrors/www.retroarchive.org/cpm/text/text.htm
Has  V 1.3 and the PC-dos version however the release covers all to a much later version
and the manual.    

See release here:
http://web.archive.org/web/20170205050727/http://www.vedit.com/cpm.htm for the release to public.

So some stuff...

**Comment by davidgiven** [comment]
Thanks, but sadly, VEDIT doesn't have any source, and has the dreaded non-commercial copyright clause in it:

> ...freely shared without licensing or royalty fees between individuals and organizations for non-commercial purposes, as long as the software's copyright messages are not altered or removed and the software is not substantially altered. For this purpose, "non-commercial" means that the sharing party will not receive any compensation for the software, and that the software is not to be included or bundled in any commercial product, software, book, electronic media or other distribution method.

Actually, this bug is obsolete, as I wrote an editor, qe. Not that I wouldn't like more, of course.

**Comment by MiguelVis** [comment]
> The last remaining piece of the core system.
> 
> I did find te, which is GPL: http://texteditors.org/cgi-bin/wiki.pl?Te
> 
> However, it currently won't build with the ACK because the ACK's stdio library doesn't work with CP/M.

Hi! I'm the author of TE.

It compiles under MESCC, my own C Compiler for Z80 derived from Small C.

I did a TE version compilable in Windows / Linux, Ansi C. I have it somewhere on my hard drive.
