### ISSUE TITLE
Build fails on macOS due to unrecognised `dd` parameter

### ISSUE THREAD

**Issue by wyan** [davidgiven/cpmish#30]
`dd` does not accept the `status=none` parameter on macOS. This causes the build to fail.

**Comment by davidgiven** [comment]
Yup, thanks --- OSX dd is painfully old.

**Comment by wyan** [comment]
I guess an alternative could be to expect macOS users to have GNU dd installed – GNU coreutils is available via homebrew, after all. Then it'd just be a matter of doing `alias dd=gdd` before building to get the correct dd version.
