### ISSUE TITLE
qe.c: open_below() should call open_above() with count

### ISSUE THREAD

**Issue by cziesler** [davidgiven/cpmish#7]
In open_below(), the call to open_above() should pass in the ```count``` variable instead of ```1```.

```c
void open_below(uint16_t count)
{
	cursor_down(1);
//	open_above(1);
	open_above(count);
}
```

**Comment by davidgiven** [comment]
Yup, fixed --- thanks!

Of course, as text_insert() currently ignores the count this is strictly academic, but that's not the point...
